### ISSUE TITLE
form buttons on ios

### ISSUE THREAD

**Issue by CydGoblin** [abhas9/ideadeck#19]
The form buttons have some are not displayed correctly on ios

![image](https://cloud.githubusercontent.com/assets/4932347/19489029/ad7c2a1c-9526-11e6-9d43-ee19d5db429e.png)

**Comment by abhas9** [comment]
I have conformed the issue in iPhone 7 safari browser. We aren't able to reproduce it in browser so it's little difficult to debug. Will take a look at it. Thanks for reporting this.

@sandeeprv @shashi20008 we have bug to hunt :)
