### ISSUE TITLE
Export a landing page source code

### ISSUE THREAD

**Issue by bingit2** [abhas9/ideadeck#20]
Hey there,

Is there any we can export a created landing page to host it on our own server?

Thanks,

**Comment by abhas9** [comment]
Hi @itsjackynguyen,

As of now, we don't have a direct/clean way of exporting the landing page. However, you may save the source code and the CSS file manually and host it on your server.  Let me know if you are facing any problem in the process. I will be happy to help you.

Regards
Abhas

**Comment by bingit2** [comment]
@abhas9 

Hey there, thanks for letting me know. I don't know much about web dev so it's hard to do that. Can you guide me through it?

And if I do export these pages, will everything stays the same?

**Comment by abhas9** [comment]
If you are on chrome and you want to save say: https://ideadeck-10kapart2016.azurewebsites.net/abhas_tandon/

you should visit (type this in your browser address bar): 
`view-source:https://ideadeck-10kapart2016.azurewebsites.net/abhas_tandon/` and save the file as `index.html` or any other name of your choice (with HTML extension)

Next visit:
https://ideadeck-10kapart2016.azurewebsites.net/abhas_tandon/styles.css and save this file in the same folder where you saved your `HTML` file. Now if you open the `HTML` file locally everything should remain the same.

**Comment by bingit2** [comment]
Awesome. Thank you. Can you show me how to get this script going as well? I want to make a different version of IdeaDeck.

**Comment by abhas9** [comment]
Not sure what you mean by 'script going's
Do you want to run an instance of IdeaDeck?

**Comment by bingit2** [comment]
Yes, how do I install a version of IdeaDeck on my own server?

**Comment by bingit2** [comment]
Can you please write a tutorial on that?

**Comment by abhas9** [comment]
Just to clarify: 
1) Do you want to host the page which you just downloaded and saved?
2) Or you want to host IdeaDeck server which will allow others to generate new landing pages which will be hosted on the same server?

**Comment by bingit2** [comment]
I want to host IdeaDeck server which will allow others to generate new landing pages which will be hosted on the same server.

**Comment by abhas9** [comment]
This is a nodejs application, you can host it at any of the cloud providers like Microsoft azure, amazon AWS or digital ocean. 

Some reference links:
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server
https://aws.amazon.com/ec2/
https://azure.microsoft.com/en-in/
https://azure.microsoft.com/en-in/documentation/articles/app-service-web-nodejs-get-started/

If you are keen we can have a skype call regarding the same. I'll be happy to help.

**Comment by bingit2** [comment]
Wow, thank you. I would need some additional guidedance as well. Please add me on skype: tan.nguyen532

**Comment by abhas9** [comment]
Sent you a request on skype. Also, I am closing this issue here. We can take this discussion outside.
